# Generated by Django 5.0.2 on 2024-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=20)),
                ('file_field', models.FileField(upload_to='books/static/books/files')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='download_links',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/static/books/images'),
        ),
        migrations.AddField(
            model_name='book',
            name='rtf_download_link',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtf_link', to='books.file'),
        ),
        migrations.AddField(
            model_name='book',
            name='txt_download_link',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txt_link', to='books.file'),
        ),
    ]
